### ISSUE TITLE
Error taxonomy: detail errors in "spack_error"

### ISSUE THREAD

**Issue by alalazo** [spack/spack-infrastructure#441]
I started looking at failures in the last day, and I have some proposal for extending the taxonomy:
```yaml
# Spack timed out while waiting for a lock
lock_timeout:
    grep_for:
    - "Timed out waiting for a write lock after"

# A file was not found during installation    
file_not_found:
    grep_for:
    - "FileNotFoundError"
    
# A command on the system exited non-zero
system_command_failure:
    grep_for:
    - "ProcessError: Command exited with status"
    
# Couldn't fetch an archive to build a spec
fetch_error:
    fetch_error:
    - "FetchError:"
```
I also noticed a few `socket.timeout` but I see that those are already taken care of in #439 

## Notes

- The lock timeout, so far, seems to happen only on POWER
- I have seen a few cases of CMake returning -4 Does that have a particular meaning?
